name: pomoc_ukrainie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1
  flutter_typeahead: ^3.2.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets\fonts\Comfortaa-VariableFont_wght.ttf


  uses-material-design: true

  assets:
    - assets/



